name: rnaseq-r
channels:
  - bioconda
  - conda-forge
dependencies:
  - _r-mutex=1.0.1=anacondar_1
  - argcomplete=3.6.3=pyhd8ed1ab_0
  - bioconductor-annotationdbi=1.68.0=r44hdfd78af_0
  - bioconductor-biobase=2.66.0=r44h1b44f6e_0
  - bioconductor-biocgenerics=0.52.0=r44hdfd78af_3
  - bioconductor-biocparallel=1.40.0=r44hb11b259_1
  - bioconductor-biostrings=2.74.0=r44h1b44f6e_1
  - bioconductor-clusterprofiler=4.14.0=r44hdfd78af_0
  - bioconductor-data-packages=20250625=hdfd78af_0
  - bioconductor-delayedarray=0.32.0=r44h1b44f6e_1
  - bioconductor-deseq2=1.46.0=r44hb11b259_1
  - bioconductor-dose=4.0.0=r44hdfd78af_0
  - bioconductor-enhancedvolcano=1.24.0=r44hdfd78af_0
  - bioconductor-enrichplot=1.26.1=r44hdfd78af_0
  - bioconductor-fgsea=1.32.2=r44hb11b259_0
  - bioconductor-genomeinfodb=1.42.0=r44hdfd78af_2
  - bioconductor-genomeinfodbdata=1.2.13=r44hdfd78af_0
  - bioconductor-genomicranges=1.58.0=r44h1b44f6e_2
  - bioconductor-ggtree=3.14.0=r44hdfd78af_0
  - bioconductor-go.db=3.20.0=r44hdfd78af_0
  - bioconductor-gosemsim=2.32.0=r44hb11b259_1
  - bioconductor-iranges=2.40.0=r44h1b44f6e_2
  - bioconductor-keggrest=1.46.0=r44hdfd78af_0
  - bioconductor-matrixgenerics=1.18.0=r44hdfd78af_0
  - bioconductor-qvalue=2.38.0=r44hdfd78af_0
  - bioconductor-s4arrays=1.6.0=r44h1b44f6e_1
  - bioconductor-s4vectors=0.44.0=r44h1b44f6e_2
  - bioconductor-sparsearray=1.6.0=r44h1b44f6e_1
  - bioconductor-summarizedexperiment=1.36.0=r44hdfd78af_0
  - bioconductor-treeio=1.30.0=r44hdfd78af_0
  - bioconductor-ucsc.utils=1.2.0=r44hdfd78af_0
  - bioconductor-xvector=0.46.0=r44h5badf08_2
  - bioconductor-zlibbioc=1.52.0=r44h1b44f6e_2
  - bwidget=1.10.1=hce30654_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - cctools_osx-arm64=1024.3=llvm21_1_haddd2d4_9
  - clang=21.1.6=default_hf9bcbb7_0
  - clang-21=21.1.6=default_h489deba_0
  - clang_impl_osx-arm64=21.1.6=hdbf2fcc_25
  - clang_osx-arm64=21.1.6=h07b0088_25
  - clangxx=21.1.6=default_h36137df_0
  - clangxx_impl_osx-arm64=21.1.6=h7e475f0_25
  - clangxx_osx-arm64=21.1.6=h07b0088_25
  - compiler-rt=21.1.6=hce30654_0
  - compiler-rt21=21.1.6=h855ad52_0
  - compiler-rt21_osx-arm64=21.1.6=h2514db7_0
  - curl=8.17.0=hdece5d2_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - gfortran_impl_osx-arm64=14.3.0=h6d03799_1
  - gfortran_osx-arm64=14.3.0=h3c33bd0_0
  - glpk=5.0=h6d7a090_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.14=hec049ff_2
  - gsl=2.7=h6e638da_0
  - harfbuzz=12.2.0=haf38c7b_0
  - icu=75.1=hfee45f7_0
  - isl=0.26=imath32_h347afa1_101
  - jq=1.8.1=hbc156a2_0
  - krb5=1.21.3=h237132a_0
  - ld64=955.13=h5d6df6c_9
  - ld64_osx-arm64=955.13=llvm21_1_hde6573c_9
  - lerc=4.0.0=hd64df32_1
  - libasprintf=0.25.1=h493aca8_0
  - libblas=3.11.0=1_h51639a9_openblas
  - libcblas=3.11.0=1_hb0561ab_openblas
  - libclang-cpp21.1=21.1.6=default_h73dfc95_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.6=hf598326_0
  - libcxx-devel=21.1.6=h6dc3340_0
  - libcxx-headers=21.1.6=h707e725_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran-devel_osx-arm64=14.3.0=hc965647_1
  - libgfortran5=15.2.0=h742603c_1
  - libgit2=1.9.1=h3653167_1
  - libglib=2.86.1=he69a767_2
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=1_hd9741b5_openblas
  - libllvm21=21.1.6=h8e0c9ce_0
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpng=1.6.50=h280e0eb_1
  - libsqlite=3.51.1=h9a5124b_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h7dc4979_0
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.6=h4a912ad_0
  - llvm-tools=21.1.6=h855ad52_0
  - llvm-tools-21=21.1.6=h91fd4e7_0
  - make=4.4.1=hc9fafa5_2
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - ncurses=6.5=h5e97a16_3
  - oniguruma=6.9.10=h5505292_0
  - openssl=3.6.0=h5503f6c_0
  - pandoc=3.8.2.1=hce30654_0
  - pango=1.56.4=h875632e_0
  - pcre2=10.46=h7125dd6_0
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h81086ad_1
  - python=3.14.1=h40d2674_100_cp314
  - python_abi=3.14=8_cp314
  - pyyaml=6.0.3=pyh7db6752_0
  - r-abind=1.4_8=r44hc72bb7e_1
  - r-ape=5.8_1=r44hd057375_2
  - r-aplot=0.2.9=r44hc72bb7e_1
  - r-askpass=1.2.1=r44h6168396_1
  - r-assertthat=0.2.1=r44hc72bb7e_6
  - r-backports=1.5.0=r44h6168396_2
  - r-base=4.4.3=hb7b3c91_4
  - r-base64enc=0.1_3=r44h6168396_1008
  - r-bh=1.87.0_1=r44hc72bb7e_1
  - r-bit=4.6.0=r44h6168396_1
  - r-bit64=4.6.0_1=r44h6168396_1
  - r-blob=1.2.4=r44hc72bb7e_3
  - r-brew=1.0_10=r44hc72bb7e_2
  - r-brio=1.1.5=r44h6168396_2
  - r-broom=1.0.11=r44hc72bb7e_0
  - r-bslib=0.9.0=r44hc72bb7e_1
  - r-cachem=1.1.0=r44h6168396_2
  - r-callr=3.7.6=r44hc72bb7e_2
  - r-cellranger=1.1.0=r44hc72bb7e_1008
  - r-cli=3.6.5=r44hc1cd577_1
  - r-clipr=0.8.0=r44hc72bb7e_4
  - r-codetools=0.2_20=r44hc72bb7e_2
  - r-colorspace=2.1_2=r44h6168396_0
  - r-commonmark=2.0.0=r44h6168396_1
  - r-conflicted=1.2.0=r44h785f33e_3
  - r-cowplot=1.2.0=r44hc72bb7e_2
  - r-cpp11=0.5.2=r44h785f33e_2
  - r-crayon=1.5.3=r44hc72bb7e_2
  - r-credentials=2.0.3=r44hc72bb7e_1
  - r-curl=7.0.0=r44hbc3244a_1
  - r-data.table=1.17.8=r44hbd14437_1
  - r-dbi=1.2.3=r44hc72bb7e_2
  - r-dbplyr=2.5.1=r44hc72bb7e_1
  - r-desc=1.4.3=r44hc72bb7e_2
  - r-devtools=2.4.6=r44hc72bb7e_0
  - r-diffobj=0.3.6=r44h6168396_1
  - r-digest=0.6.39=r44hc1cd577_0
  - r-downlit=0.4.5=r44hc72bb7e_0
  - r-dplyr=1.1.4=r44hc1cd577_2
  - r-dtplyr=1.3.2=r44hc72bb7e_1
  - r-ellipsis=0.3.2=r44h6168396_4
  - r-evaluate=1.0.5=r44hc72bb7e_1
  - r-fansi=1.0.7=r44h6168396_0
  - r-farver=2.1.2=r44hc1cd577_2
  - r-fastmap=1.2.0=r44hc1cd577_2
  - r-fastmatch=1.1_6=r44h6168396_1
  - r-fontawesome=0.5.3=r44hc72bb7e_1
  - r-forcats=1.0.1=r44hc72bb7e_0
  - r-formatr=1.14=r44hc72bb7e_3
  - r-fs=1.6.6=r44hc1cd577_1
  - r-futile.logger=1.4.3=r44hc72bb7e_1007
  - r-futile.options=1.0.1=r44hc72bb7e_1006
  - r-gargle=1.6.0=r44h785f33e_1
  - r-generics=0.1.4=r44hc72bb7e_1
  - r-gert=2.2.0=r44hbcc5cb6_0
  - r-ggforce=0.5.0=r44hc1cd577_1
  - r-ggfun=0.2.0=r44hc72bb7e_1
  - r-ggnewscale=0.5.2=r44hc72bb7e_1
  - r-ggplot2=4.0.1=r44h785f33e_0
  - r-ggplotify=0.1.3=r44hc72bb7e_1
  - r-ggrepel=0.9.6=r44hc1cd577_2
  - r-ggtangle=0.0.9=r44hc72bb7e_0
  - r-gh=1.5.0=r44hc72bb7e_1
  - r-gitcreds=0.1.2=r44hc72bb7e_4
  - r-glue=1.8.0=r44h6168396_1
  - r-googledrive=2.1.2=r44hc72bb7e_1
  - r-googlesheets4=1.1.2=r44h785f33e_1
  - r-gridgraphics=0.5_1=r44hc72bb7e_4
  - r-gson=0.1.0=r44hc72bb7e_3
  - r-gtable=0.3.6=r44hc72bb7e_1
  - r-haven=2.5.5=r44h82072fd_1
  - r-highr=0.11=r44hc72bb7e_2
  - r-hms=1.1.4=r44hc72bb7e_0
  - r-htmltools=0.5.9=r44hc1cd577_0
  - r-htmlwidgets=1.6.4=r44h785f33e_4
  - r-httpuv=1.6.16=r44h82072fd_1
  - r-httr=1.4.7=r44hc72bb7e_2
  - r-httr2=1.2.1=r44hc72bb7e_1
  - r-ids=1.0.1=r44hc72bb7e_5
  - r-igraph=2.1.4=r44hc65f240_2
  - r-ini=0.3.1=r44hc72bb7e_1007
  - r-isoband=0.2.7=r44hc1cd577_4
  - r-jquerylib=0.1.4=r44hc72bb7e_4
  - r-jsonlite=2.0.0=r44h6168396_1
  - r-knitr=1.50=r44hc72bb7e_1
  - r-labeling=0.4.3=r44hc72bb7e_2
  - r-lambda.r=1.2.4=r44hc72bb7e_5
  - r-later=1.4.4=r44hc1cd577_1
  - r-lattice=0.22_7=r44h6168396_1
  - r-lazyeval=0.2.2=r44h6168396_6
  - r-lifecycle=1.0.4=r44hc72bb7e_2
  - r-locfit=1.5_9.12=r44h6168396_1
  - r-lubridate=1.9.4=r44h6168396_1
  - r-magrittr=2.0.4=r44h6168396_0
  - r-mass=7.3_65=r44h6168396_0
  - r-matrix=1.7_4=r44hb2d3ebe_1
  - r-matrixstats=1.5.0=r44h6168396_1
  - r-memoise=2.0.1=r44hc72bb7e_4
  - r-mime=0.13=r44h6168396_1
  - r-miniui=0.1.2=r44hc72bb7e_1
  - r-modelr=0.1.11=r44hc72bb7e_3
  - r-munsell=0.5.1=r44hc72bb7e_2
  - r-nlme=3.1_168=r44hd097873_1
  - r-openssl=2.3.4=r44h7a56cc5_0
  - r-otel=0.2.0=r44hc72bb7e_1
  - r-patchwork=1.3.2=r44hc72bb7e_1
  - r-pheatmap=1.0.13=r44hc72bb7e_1
  - r-pillar=1.11.1=r44hc72bb7e_0
  - r-pkgbuild=1.4.8=r44hc72bb7e_1
  - r-pkgconfig=2.0.3=r44hc72bb7e_5
  - r-pkgdown=2.2.0=r44hc72bb7e_0
  - r-pkgload=1.4.1=r44hc72bb7e_0
  - r-plogr=0.2.0=r44hc72bb7e_1007
  - r-plyr=1.8.9=r44hc1cd577_3
  - r-png=0.1_8=r44h4299753_3
  - r-polyclip=1.10_7=r44hc1cd577_1
  - r-praise=1.0.0=r44hc72bb7e_1009
  - r-prettyunits=1.2.0=r44hc72bb7e_2
  - r-processx=3.8.6=r44h6168396_1
  - r-profvis=0.4.0=r44h6168396_1
  - r-progress=1.2.3=r44hc72bb7e_2
  - r-promises=1.5.0=r44hc72bb7e_1
  - r-ps=1.9.1=r44h6168396_1
  - r-purrr=1.2.0=r44h6168396_0
  - r-r.methodss3=1.8.2=r44hc72bb7e_4
  - r-r.oo=1.27.1=r44hc72bb7e_1
  - r-r.utils=2.13.0=r44hc72bb7e_1
  - r-r6=2.6.1=r44hc72bb7e_1
  - r-ragg=1.5.0=r44hf65f6a8_1
  - r-rappdirs=0.3.3=r44h6168396_4
  - r-rcmdcheck=1.4.0=r44h785f33e_4
  - r-rcolorbrewer=1.1_3=r44h785f33e_4
  - r-rcpp=1.1.0=r44hc1cd577_1
  - r-rcpparmadillo=15.2.2_1=r44ha64934e_0
  - r-rcppeigen=0.3.4.0.2=r44hd057375_1
  - r-readr=2.1.6=r44hc1cd577_0
  - r-readxl=1.4.5=r44hf730888_1
  - r-rematch=2.0.0=r44hc72bb7e_2
  - r-rematch2=2.1.2=r44hc72bb7e_5
  - r-remotes=2.5.0=r44hc72bb7e_2
  - r-reprex=2.1.1=r44hc72bb7e_2
  - r-reshape2=1.4.5=r44hc1cd577_0
  - r-rlang=1.1.6=r44hc1cd577_1
  - r-rmarkdown=2.30=r44hc72bb7e_0
  - r-roxygen2=7.3.3=r44hc1cd577_1
  - r-rprojroot=2.1.1=r44hc72bb7e_1
  - r-rsqlite=2.4.5=r44hc1cd577_0
  - r-rstudioapi=0.17.1=r44hc72bb7e_1
  - r-rversions=3.0.0=r44hc72bb7e_0
  - r-rvest=1.0.5=r44hc72bb7e_1
  - r-s7=0.2.1=r44h6168396_0
  - r-sass=0.4.10=r44hc1cd577_1
  - r-scales=1.4.0=r44hc72bb7e_1
  - r-scatterpie=0.2.6=r44hc72bb7e_1
  - r-selectr=0.5_0=r44hc72bb7e_0
  - r-sessioninfo=1.2.3=r44hc72bb7e_1
  - r-shiny=1.12.0=r44h785f33e_0
  - r-snow=0.4_4=r44hc72bb7e_4
  - r-sourcetools=0.1.7_1=r44hc1cd577_3
  - r-stringi=1.8.7=r44he9eb878_1
  - r-stringr=1.6.0=r44h785f33e_0
  - r-sys=3.4.3=r44h6168396_1
  - r-systemfonts=1.3.1=r44h288a467_0
  - r-testthat=3.3.1=r44hc1cd577_0
  - r-textshaping=1.0.4=r44h288a467_0
  - r-tibble=3.3.0=r44h6168396_1
  - r-tidyr=1.3.1=r44hc1cd577_2
  - r-tidyselect=1.2.1=r44hc72bb7e_2
  - r-tidytree=0.4.6=r44hc72bb7e_2
  - r-tidyverse=2.0.0=r44h785f33e_3
  - r-timechange=0.3.0=r44hc1cd577_2
  - r-tinytex=0.58=r44hc72bb7e_0
  - r-tweenr=2.0.3=r44hc1cd577_2
  - r-tzdb=0.5.0=r44hc1cd577_2
  - r-urlchecker=1.0.1=r44hc72bb7e_4
  - r-usethis=3.2.1=r44hc72bb7e_1
  - r-utf8=1.2.6=r44h6168396_1
  - r-uuid=1.2_1=r44h6168396_1
  - r-vctrs=0.6.5=r44hc1cd577_2
  - r-viridislite=0.4.2=r44hc72bb7e_3
  - r-vroom=1.6.7=r44hc1cd577_0
  - r-waldo=0.6.2=r44hc72bb7e_1
  - r-whisker=0.4.1=r44hc72bb7e_3
  - r-withr=3.0.2=r44hc72bb7e_1
  - r-xfun=0.54=r44hc1cd577_0
  - r-xml2=1.5.0=r44h7a605a7_0
  - r-xopen=1.0.1=r44hc72bb7e_2
  - r-xtable=1.8_4=r44hc72bb7e_7
  - r-yaml=2.3.11=r44h6168396_0
  - r-yulab.utils=0.2.2=r44hc72bb7e_0
  - r-zip=2.3.3=r44h6168396_1
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - sigtool=0.1.3=h44b9a77_0
  - tapi=1300.6.5=h03f4b80_0
  - tk=8.6.13=h892fb3f_3
  - tktable=2.10=h3c7de25_7
  - toml=0.10.2=pyhcf101f3_3
  - tomlkit=0.13.3=pyha770c72_0
  - tzdata=2025b=h78e105d_0
  - xmltodict=1.0.2=pyhcf101f3_0
  - yaml=0.2.5=h925e9cb_3
  - yq=3.4.3=pyhe01879c_2
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=h6491c7d_2

prefix: "/Users/mucyo/opt/miniconda3/envs/rnaseq-r"
