name: rnaseq-r
channels:
  - bioconda
  - conda-forge
dependencies:
  - r-base=4.4
  - bioconductor-deseq2
  - bioconductor-clusterprofiler
  - bioconductor-enhancedvolcano
  - bioconductor-enrichplot
  - bioconductor-org.mm.eg.db
  - r-pheatmap
  - r-ggplot2
  - r-ggrepel
  - cairo
  - fonts-conda-forge
prefix: /Users/mucyo/opt/miniconda3/envs/rnaseq-r
